server:
  port: 6201
spring:
  application:
    name: microservice-consumer-movie-Feign
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6203/eureka
  instance:
      prefer-ip-address: true
feign:
  hystrix:
    enabled: true